# Copy this to Fastfile in your fastlane
default_platform(:ios)

# Do not change the outputName variable value. It's paired bitrise scripts.
outputPath = "./build"
outputName = "ipa"

platform :ios do
  lane :bump_and_build do |options|
    increment_build_number
    gym(
      scheme: options[:scheme],
      output_directory: outputPath,
      output_name: outputName + ".ipa"
    )
  end
end